// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAifctIl0cakTUL8mzpvaZnC2FIvfcwHqM',
    appId: '1:93328373064:web:b5cf6670aae9773abe2f7d',
    messagingSenderId: '93328373064',
    projectId: 'studentolgasi',
    authDomain: 'studentolgasi.firebaseapp.com',
    storageBucket: 'studentolgasi.appspot.com',
    measurementId: 'G-X5PSXG3JHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3B_KZg3QeDHgVD5u7M-HI7194gw5eXa0',
    appId: '1:93328373064:android:89b405cadeb82159be2f7d',
    messagingSenderId: '93328373064',
    projectId: 'studentolgasi',
    storageBucket: 'studentolgasi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDESnX-4r2gC2M1xkiueTVGWwU662BBt1Y',
    appId: '1:93328373064:ios:f60f5fdbb737eaa0be2f7d',
    messagingSenderId: '93328373064',
    projectId: 'studentolgasi',
    storageBucket: 'studentolgasi.appspot.com',
    iosBundleId: 'com.example.studentoglasiMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDESnX-4r2gC2M1xkiueTVGWwU662BBt1Y',
    appId: '1:93328373064:ios:f60f5fdbb737eaa0be2f7d',
    messagingSenderId: '93328373064',
    projectId: 'studentolgasi',
    storageBucket: 'studentolgasi.appspot.com',
    iosBundleId: 'com.example.studentoglasiMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAifctIl0cakTUL8mzpvaZnC2FIvfcwHqM',
    appId: '1:93328373064:web:74620e6409295ba8be2f7d',
    messagingSenderId: '93328373064',
    projectId: 'studentolgasi',
    authDomain: 'studentolgasi.firebaseapp.com',
    storageBucket: 'studentolgasi.appspot.com',
    measurementId: 'G-VN4FHCLRBG',
  );
}
